import { cert,getApps,initializeApp } from 'firebase-admin/app'
import { getAuth } from 'firebase-admin/auth'
import { getFirestore } from 'firebase-admin/firestore'
import { PASSWORD_RESET_TEMPLATE,emailHtml,fillTemplate,ryfieldsResetLink,sendEmail,type EmailTemplate } from '../../functions/lib/shared/email.js'

if(!getApps().length){const projectId=process.env.FIREBASE_ADMIN_PROJECT_ID,clientEmail=process.env.FIREBASE_ADMIN_CLIENT_EMAIL,privateKey=process.env.FIREBASE_ADMIN_PRIVATE_KEY?.replace(/\\n/g,'\n');initializeApp(projectId&&clientEmail&&privateKey?{credential:cert({projectId,clientEmail,privateKey})}:undefined)}
const generic=()=>new Response(JSON.stringify({ok:true,message:'If an account exists for that address, reset instructions are on their way.'}),{status:200,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}})
export default async(req:Request)=>{if(req.method!=='POST')return new Response('Method not allowed',{status:405});try{const body=await req.json() as{email?:string},email=String(body.email||'').trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))return generic();const apiKey=process.env.RESEND_API_KEY,from=process.env.RESEND_FROM,baseUrl=process.env.APP_BASE_URL||'https://ryfields-gym.netlify.app';if(!apiKey||!from)throw new Error('Resend is not configured.');const user=await getAuth().getUserByEmail(email),memberSnap=await getFirestore().collection('members').where('email','==',email).limit(1).get(),firstName=String(memberSnap.docs[0]?.get('firstName')||user.displayName?.split(' ')[0]||'there'),templateSnap=await getFirestore().collection('emailTemplates').doc('password-reset').get(),template=templateSnap.exists?templateSnap.data() as EmailTemplate:PASSWORD_RESET_TEMPLATE,firebaseLink=await getAuth().generatePasswordResetLink(email,{url:`${baseUrl}/login`}),resetLink=ryfieldsResetLink(firebaseLink,baseUrl),variables={firstName,resetLink},subject=fillTemplate(template.subject,variables),text=fillTemplate(template.body,variables);await sendEmail({to:email,from,apiKey,subject,text,html:emailHtml(template.body,variables)});return generic()}catch(error){const code=(error as{code?:string}).code;if(code!=='auth/user-not-found')console.error('Password reset email failed',error);return generic()}}
export const config={rateLimit:{windowLimit:5,windowSize:300,aggregateBy:['ip']}}
