import { CheckCircle2,ChevronDown,Dumbbell,Heart,PartyPopper,Scale,Sparkles,TrendingUp } from 'lucide-react'
import { useMemo,useState,type FormEvent } from 'react'
import { httpsCallable } from '../../lib/netlifyFunctions'
import { firebaseConfigured,functions } from '../../lib/firebase'

type Stamp={toDate():Date}
type Entry={kind:'weight'|'strength'|'activity'|'wellness';value?:number;reps?:number;label?:string;rating?:number;loggedAt?:Stamp|Date}
export type GoalProgress={startValue?:number;targetValue?:number;unit?:string;focus?:string;weeklyTarget?:number;startedAt?:Stamp|Date;lastEntryAt?:Stamp|Date;entries?:Entry[]}
type GoalMember={firstName:string;goal?:string;goalProgress?:GoalProgress}
const details:Record<string,{label:string;intro:string;icon:typeof Scale}>= {
  weight_loss:{label:'Weight loss',intro:'Small, steady steps count. A weekly check-in gives you the clearest picture.',icon:Scale},
  muscle:{label:'Muscle building',intro:'Track one key exercise to start. Consistency and good form beat chasing numbers.',icon:Dumbbell},
  fun:{label:'Fun & events',intro:'Keep movement enjoyable. Classes, events and trying something new all count.',icon:PartyPopper},
  wellness:{label:'Wellness',intro:'Notice how movement affects your energy and mood, without judging individual days.',icon:Heart},
}
const dateOf=(value?:Stamp|Date)=>!value?null:value instanceof Date?value:value.toDate()
const ago=(value?:Stamp|Date)=>{const date=dateOf(value);if(!date)return'';const days=Math.max(0,Math.floor((Date.now()-date.getTime())/864e5));return days===0?'Today':days===1?'Yesterday':`${days} days ago`}

export function GoalJourneyCard({member,memberId}:{member:GoalMember;memberId:string|null}){
  const goal=member.goal||'',meta=details[goal]
  const progress=member.goalProgress||{},entries=progress.entries||[]
  const[open,setOpen]=useState(!progress.startedAt),[saving,setSaving]=useState(false),[message,setMessage]=useState('')
  const[start,setStart]=useState(progress.startValue?.toString()||''),[target,setTarget]=useState(progress.targetValue?.toString()||''),[focus,setFocus]=useState(progress.focus||(goal==='fun'?'Classes and events':goal==='wellness'?'More energy':'')),[weekly,setWeekly]=useState(progress.weeklyTarget?.toString()||'2')
  const[value,setValue]=useState(''),[reps,setReps]=useState(''),[rating,setRating]=useState(0),[activity,setActivity]=useState('Tried a class')
  const[changingGoal,setChangingGoal]=useState(false)
  const latest=entries.at(-1)
  const pct=useMemo(()=>{if(goal==='weight_loss'&&progress.startValue&&progress.targetValue&&latest?.value!==undefined){const total=progress.startValue-progress.targetValue;if(total<=0)return 0;return Math.max(0,Math.min(100,Math.round((progress.startValue-latest.value)/total*100)))}if(goal==='muscle'&&progress.startValue&&progress.targetValue&&latest?.value!==undefined){const total=progress.targetValue-progress.startValue;if(total<=0)return 0;return Math.max(0,Math.min(100,Math.round((latest.value-progress.startValue)/total*100)))}return Math.min(100,entries.length*20)},[entries.length,goal,latest?.value,progress.startValue,progress.targetValue])
  if(!meta)return null
  const Icon=meta.icon
  async function call(data:Record<string,unknown>){if(!memberId)return;setSaving(true);setMessage('');try{if(firebaseConfigured)await httpsCallable(functions,'updateGoalProgress')({memberId,...data});setMessage('Saved — another step in the right direction.');setOpen(false);setValue('');setReps('');setRating(0)}catch(err){setMessage(err instanceof Error&&err.message?err.message:'That did not save — please try again.')}finally{setSaving(false)}}
  async function setup(event:FormEvent){event.preventDefault();const setup:Record<string,unknown>={weeklyTarget:Number(weekly)||2};if(goal==='weight_loss'||goal==='muscle'){setup.startValue=Number(start);setup.targetValue=Number(target);setup.unit='kg'}if(focus)setup.focus=focus;await call({setup})}
  async function log(){if(goal==='weight_loss')await call({entry:{kind:'weight',value:Number(value)}});if(goal==='muscle')await call({entry:{kind:'strength',value:Number(value),reps:Number(reps)||undefined,label:progress.focus||'Key exercise'}});if(goal==='fun')await call({entry:{kind:'activity',label:activity,value:1}});if(goal==='wellness')await call({entry:{kind:'wellness',rating}})}
  async function changeGoal(next:string){if(!memberId||next===goal)return;setSaving(true);setMessage('');try{if(firebaseConfigured)await httpsCallable(functions,'setMemberJourney')({memberId,goal:next});setChangingGoal(false)}catch{setMessage('Your goal could not be changed just now.')}finally{setSaving(false)}}
  const complete=pct>=100
  return <article className={`panel goal-journey goal-${goal}`}>
    <div className="goal-journey-head"><span className="goal-icon"><Icon/></span><div><p className="eyebrow">Your goal</p><h2>{meta.label}</h2></div>{progress.startedAt&&<button className="secondary goal-toggle" onClick={()=>setOpen(v=>!v)}>{open?'Close':'Check in'} <ChevronDown/></button>}</div>
    <button type="button" className="goal-change-link" onClick={()=>setChangingGoal(v=>!v)}>{changingGoal?'Keep this goal':'Change my goal'}</button>
    {changingGoal&&<div className="goal-change"><strong>Choose a new focus</strong><p>Your previous check-ins stay safely in your history.</p><div>{Object.entries(details).map(([key,item])=><button type="button" disabled={saving||key===goal} className={key===goal?'selected':''} onClick={()=>changeGoal(key)} key={key}>{item.label}</button>)}</div></div>}
    <p>{meta.intro}</p>
    {progress.startedAt&&<><div className="goal-progress"><div><i style={{width:`${pct}%`}}/></div><strong>{complete?'Goal reached!':`${pct}% progress`}</strong><small>{latest?.loggedAt?`Last check-in ${ago(latest.loggedAt)}`:'Ready for your first check-in'}</small></div>{complete&&<div className="goal-celebrate"><Sparkles/><span><strong>You’ve smashed it, {member.firstName}!</strong> Take a moment to celebrate—and choose your next step when you’re ready.</span></div>}</>}
    {open&&!progress.startedAt&&<form className="goal-form" onSubmit={setup}><h3>Make it yours</h3>{goal==='weight_loss'&&<div className="form-grid"><label>Starting weight (kg)<input required type="number" min="20" max="500" step="0.1" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Target weight (kg)<input required type="number" min="20" max="500" step="0.1" value={target} onChange={e=>setTarget(e.target.value)}/></label></div>}{goal==='muscle'&&<><label>Exercise to track<input required placeholder="e.g. Leg press" value={focus} onChange={e=>setFocus(e.target.value)}/></label><div className="form-grid"><label>Starting weight (kg)<input required type="number" min="0.5" max="1000" step="0.5" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Target weight (kg)<input required type="number" min="0.5" max="1000" step="0.5" value={target} onChange={e=>setTarget(e.target.value)}/></label></div></>}{goal==='fun'&&<label>What sounds most fun?<select value={focus} onChange={e=>setFocus(e.target.value)}><option value="Classes and events">Classes and events</option><option value="Trying new activities">Trying new activities</option><option value="Meeting people">Meeting people</option><option value="A regular routine">A regular routine</option></select></label>}{goal==='wellness'&&<label>What would you most like to improve?<select value={focus} onChange={e=>setFocus(e.target.value)}><option value="More energy">More energy</option><option value="Better mood">Better mood</option><option value="Less stress">Less stress</option><option value="Mobility and confidence">Mobility and confidence</option></select></label>}<label>Visits or activities per week<input required type="number" min="1" max="14" value={weekly} onChange={e=>setWeekly(e.target.value)}/></label><button className="primary" disabled={saving}>{saving?'Saving…':'Start my journey'}</button></form>}
    {open&&progress.startedAt&&<div className="goal-form"><h3>Quick check-in</h3>{goal==='weight_loss'&&<><label>Weight today (kg)<input type="number" min="20" max="500" step="0.1" value={value} onChange={e=>setValue(e.target.value)}/></label><p className="goal-tip">Tip: weekly readings are more useful than daily fluctuations. Consistency beats perfection.</p></>}{goal==='muscle'&&<div className="form-grid"><label>{progress.focus||'Exercise'} weight (kg)<input type="number" min="0.5" max="1000" step="0.5" value={value} onChange={e=>setValue(e.target.value)}/></label><label>Repetitions<input type="number" min="1" max="1000" value={reps} onChange={e=>setReps(e.target.value)}/></label></div>}{goal==='fun'&&<label>What did you do?<select value={activity} onChange={e=>setActivity(e.target.value)}><option>Tried a class</option><option>Attended an event</option><option>Tried something new</option><option>Trained with a friend</option><option>Had a great gym session</option></select></label>}{goal==='wellness'&&<><p>How are your energy and mood feeling?</p><div className="wellness-rating">{[1,2,3,4,5].map(n=><button key={n} className={rating===n?'selected':''} onClick={()=>setRating(n)} aria-label={`${n} out of 5`}>{['😞','🙁','😐','🙂','😄'][n-1]}</button>)}</div></>}<button className="primary" disabled={saving||(goal==='wellness'?!rating:(goal==='weight_loss'||goal==='muscle')&&!Number(value))} onClick={log}><CheckCircle2/> {saving?'Saving…':'Save check-in'}</button></div>}
    {message&&<p className="goal-message">{message}</p>}
    {!open&&progress.startedAt&&!complete&&<button className="goal-nudge" onClick={()=>setOpen(true)}><TrendingUp/> Log a quick update</button>}
  </article>
}
