import { readFile } from 'node:fs/promises'
import { afterAll,beforeAll,beforeEach,describe,it } from 'vitest'
import { assertFails,assertSucceeds,initializeTestEnvironment,type RulesTestEnvironment } from '@firebase/rules-unit-testing'
import { collectionGroup,doc,getDoc,getDocs,query,setDoc,where } from 'firebase/firestore'

let environment:RulesTestEnvironment
beforeAll(async()=>{environment=await initializeTestEnvironment({projectId:'ryfields-rules-test',firestore:{rules:await readFile('firestore.rules','utf8'),host:'127.0.0.1',port:8080}})})
afterAll(async()=>environment.cleanup())
beforeEach(async()=>{await environment.clearFirestore();await environment.withSecurityRulesDisabled(async context=>{const db=context.firestore();await Promise.all([setDoc(doc(db,'members/member-a'),{authUid:'user-a',firstName:'Alex'}),setDoc(doc(db,'members/member-b'),{authUid:'user-b',firstName:'Sam'}),setDoc(doc(db,'members/member-a/notes/note-1'),{body:'Private note'}),setDoc(doc(db,'payments/payment-a'),{memberId:'member-a',amountMinor:4500}),setDoc(doc(db,'classSessions/session-1'),{nameSnapshot:'Yoga'}),setDoc(doc(db,'classSessions/session-1/bookings/member-a'),{memberId:'member-a',status:'confirmed'}),setDoc(doc(db,'visits/visit-a'),{memberId:'member-a'})])})})

describe('Firestore role isolation',()=>{
  it('lets a member read only their own member record',async()=>{const db=environment.authenticatedContext('user-a',{role:'member',memberId:'member-a'}).firestore();await assertSucceeds(getDoc(doc(db,'members/member-a')));await assertFails(getDoc(doc(db,'members/member-b')))})
  it('keeps staff notes private from members',async()=>{const member=environment.authenticatedContext('user-a',{role:'member',memberId:'member-a'}).firestore(),staff=environment.authenticatedContext('staff-1',{role:'staff'}).firestore();await assertFails(getDoc(doc(member,'members/member-a/notes/note-1')));await assertSucceeds(getDoc(doc(staff,'members/member-a/notes/note-1')))})
  it('isolates payments, visits and bookings by member claim',async()=>{const own=environment.authenticatedContext('user-a',{role:'member',memberId:'member-a'}).firestore(),other=environment.authenticatedContext('user-b',{role:'member',memberId:'member-b'}).firestore();for(const path of ['payments/payment-a','visits/visit-a','classSessions/session-1/bookings/member-a']){await assertSucceeds(getDoc(doc(own,path)));await assertFails(getDoc(doc(other,path)))}await assertSucceeds(getDocs(query(collectionGroup(own,'bookings'),where('memberId','==','member-a'),where('status','in',['confirmed','waitlisted']))));await assertFails(getDocs(query(collectionGroup(other,'bookings'),where('memberId','==','member-a'),where('status','in',['confirmed','waitlisted']))))})
  it('denies browser writes even to owned records',async()=>{const db=environment.authenticatedContext('user-a',{role:'member',memberId:'member-a'}).firestore();await assertFails(setDoc(doc(db,'payments/fake'),{memberId:'member-a',status:'confirmed'}));await assertFails(setDoc(doc(db,'visits/fake'),{memberId:'member-a'}));await assertFails(setDoc(doc(db,'classSessions/session-1/bookings/member-a'),{status:'cancelled'}))})
  it('allows staff operational reads but reserves audit logs for admins',async()=>{await environment.withSecurityRulesDisabled(async context=>setDoc(doc(context.firestore(),'auditLogs/log-1'),{action:'test'}));const staff=environment.authenticatedContext('staff-1',{role:'staff'}).firestore(),admin=environment.authenticatedContext('admin-1',{role:'admin'}).firestore();await assertSucceeds(getDoc(doc(staff,'members/member-a')));await assertSucceeds(getDoc(doc(staff,'payments/payment-a')));await assertFails(getDoc(doc(staff,'auditLogs/log-1')));await assertSucceeds(getDoc(doc(admin,'auditLogs/log-1')))})
  it('keeps each cash-import workspace private to its administrator account',async()=>{const own=environment.authenticatedContext('admin-1',{role:'admin'}).firestore(),other=environment.authenticatedContext('admin-2',{role:'admin'}).firestore(),staff=environment.authenticatedContext('staff-1',{role:'staff'}).firestore(),workspace=doc(own,'cashImportWorkspaces/admin-1'),month=doc(own,'cashImportWorkspaces/admin-1/months/2026-07');await assertSucceeds(setDoc(workspace,{activeMonth:'2026-07'}));await assertSucceeds(setDoc(month,{result:{month:'2026-07'},monthState:{sessions:[],checks:{}}}));await assertSucceeds(getDoc(workspace));await assertSucceeds(getDoc(month));await assertFails(getDoc(doc(other,'cashImportWorkspaces/admin-1')));await assertFails(setDoc(doc(other,'cashImportWorkspaces/admin-1'),{activeMonth:'2026-08'}));await assertFails(getDoc(doc(staff,'cashImportWorkspaces/staff-1')))})
})
