import { Search, UserPlus, X } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'
import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { createMember, subscribeToMembers } from './memberService'
import { goalLabel, statusLabel, type Member, type MembershipStatus, type NewMember } from './types'
import { MemberProfile } from './MemberProfile'
import { subscribeToMembershipTypes } from '../memberships/membershipService'
import type { MembershipType } from '../memberships/types'

const demo: Member[] = [
  {id:'1',memberNumber:'RYF-1042',firstName:'Alex',lastName:'Morgan',email:'alex@example.com',membershipTypeId:'full',membershipTypeName:'Full Gym',membershipStatus:'active'},
  {id:'2',memberNumber:'RYF-1041',firstName:'Sam',lastName:'Taylor',email:'sam@example.com',membershipTypeId:'classes',membershipTypeName:'Classes',membershipStatus:'active'},
  {id:'3',memberNumber:'RYF-1039',firstName:'Jordan',lastName:'Lee',email:'jordan@example.com',membershipTypeId:'full',membershipTypeName:'Full Gym',membershipStatus:'payment_failed'},
]
const empty: NewMember={firstName:'',lastName:'',email:'',phone:'',membershipTypeId:''}

export function MembersPage(){
  const [members,setMembers]=useState<Member[]>(demo),[selected,setSelected]=useState<Member|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState<'all'|MembershipStatus>('all'),[open,setOpen]=useState(false),[form,setForm]=useState(empty),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[uncheckedOnly,setUncheckedOnly]=useState(false),[unclaimedOnly,setUnclaimedOnly]=useState(false),[planFilter,setPlanFilter]=useState('all'),[issuesOnly,setIssuesOnly]=useState(false),[newOnly,setNewOnly]=useState(false)
  const [searchParams,setSearchParams]=useSearchParams()
  useEffect(()=>{const s=searchParams.get('status');if(s&&s in statusLabel)setFilter(s as MembershipStatus);const p=searchParams.get('plan');if(p)setPlanFilter(p);setIssuesOnly(searchParams.get('issues')==='1');setNewOnly(searchParams.get('new')==='1')},[searchParams])
  useEffect(()=>subscribeToMembers(items=>{if(items.length)setMembers(items)},()=>setMessage('Live member updates are temporarily unavailable.')) ,[])
  useEffect(()=>{const id=searchParams.get('member');if(id&&!selected){const member=members.find(item=>item.id===id);if(member)setSelected(member)}},[members,searchParams,selected])
  const [plans,setPlans]=useState<MembershipType[]>([])
  useEffect(()=>subscribeToMembershipTypes(items=>setPlans(items.filter(p=>p.active)),()=>{}),[])
  useEffect(()=>{if(open&&!form.membershipTypeId&&plans.length)setForm(current=>({...current,membershipTypeId:plans[0].id}))},[open,plans,form.membershipTypeId])
  const shown=useMemo(()=>{const startToday=new Date();startToday.setHours(0,0,0,0);const created=(m:Member)=>m.createdAt?(m.createdAt instanceof Date?m.createdAt:m.createdAt.toDate()):null;return members.filter(m=>(filter==='all'||m.membershipStatus===filter||(filter==='active'&&m.membershipStatus==='payment_failed'))&&(planFilter==='all'||(planFilter==='none'?!m.membershipTypeId:m.membershipTypeId===planFilter))&&(!uncheckedOnly||m.needsReview===true)&&(!unclaimedOnly||!m.authUid)&&(!issuesOnly||m.membershipStatus==='payment_failed'||(m.membershipStatus==='cancelled'&&!m.cancellationAcknowledged))&&(!newOnly||(()=>{const d=created(m);return!!d&&d>=startToday})())&&`${m.firstName} ${m.lastName} ${m.email} ${m.memberNumber}`.toLowerCase().includes(query.toLowerCase()))},[members,query,filter,planFilter,uncheckedOnly,unclaimedOnly,issuesOnly,newOnly])
  const uncheckedCount=members.filter(m=>m.needsReview===true).length,unclaimedCount=members.filter(m=>!m.authUid).length
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setMessage('');try{const result=await createMember(form);setMembers(current=>[{...form,id:result.id,memberNumber:result.memberNumber,membershipStatus:'pending_payment',membershipTypeName:plans.find(p=>p.id===form.membershipTypeId)?.name||form.membershipTypeId},...current]);setForm(empty);setOpen(false);setMessage('Member created. Payment setup is the next step.')}catch{setMessage('The member could not be created. Please try again.')}finally{setSaving(false)}}
  if(selected)return <MemberProfile member={selected} onBack={()=>{setSelected(null);const next=new URLSearchParams(searchParams);next.delete('member');setSearchParams(next)}} onChange={updated=>{setSelected(updated);setMembers(current=>current.map(m=>m.id===updated.id?updated:m))}}/>
  return <><header className="page-head"><div><p className="eyebrow">Member management</p><h1>Members</h1><p>Search, review and manage the Ryfields Gym community.</p></div><button className="primary" onClick={()=>setOpen(true)}><UserPlus/> Add member</button></header>{message&&<div className="notice" role="status">{message}</div>}{issuesOnly&&<div className="notice" role="status">Showing members with payment issues only. <button type="button" className="link-button" onClick={()=>setIssuesOnly(false)}>Show all members</button></div>}{newOnly&&<div className="notice" role="status">Showing members who joined today. <button type="button" className="link-button" onClick={()=>setNewOnly(false)}>Show all members</button></div>}<article className="panel members-panel"><div className="member-tools"><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, email or member number…"/></label><select value={filter} onChange={e=>{setFilter(e.target.value as typeof filter);setIssuesOnly(false)}}><option value="all">All statuses</option>{Object.entries(statusLabel).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><select value={planFilter} onChange={e=>{setPlanFilter(e.target.value);setIssuesOnly(false)}}><option value="all">All plans</option>{plans.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}<option value="none">No membership</option></select><label className="unchecked-toggle"><input type="checkbox" checked={uncheckedOnly} onChange={e=>setUncheckedOnly(e.target.checked)}/> Needs review{uncheckedCount?` (${uncheckedCount})`:''}</label><label className="unchecked-toggle"><input type="checkbox" checked={unclaimedOnly} onChange={e=>setUnclaimedOnly(e.target.checked)}/> Unclaimed only{unclaimedCount?` (${unclaimedCount})`:''}</label></div><div className="member-table"><div className="table-head"><span>Member</span><span>Membership</span><span>Status</span></div>{shown.map(m=><button className="table-row" key={m.id} onClick={()=>setSelected(m)}><span><b>{m.firstName[0]}{m.lastName[0]}</b><span><strong>{m.firstName} {m.lastName}{m.needsReview&&<i className="check-dot" title={m.reviewReason||'Needs staff review'}/>}</strong><small>{m.email}</small>{m.needsReview&&<span className="unclaimed-pill">Review: {m.reviewReason||'Member update'}</span>}{!m.authUid&&<span className="unclaimed-pill">Unclaimed</span>}{newOnly&&m.goal&&<span className="goal-pill">Here for: {goalLabel[m.goal]||m.goal}</span>}</span></span><span>{m.membershipTypeName||m.membershipTypeId}</span><em className={`status-${m.membershipStatus}`}>{statusLabel[m.membershipStatus]}</em></button>)}{!shown.length&&<p className="no-results">No members match this search.</p>}</div></article>
    {open&&<div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="add-member-title"><button className="modal-close" onClick={()=>setOpen(false)} aria-label="Close"><X/></button><p className="eyebrow">New member</p><h2 id="add-member-title">Add member details</h2><form onSubmit={submit}><div className="form-grid"><label>First name<input required value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/></label><label>Last name<input required value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/></label></div><label>Email address<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Phone number<input type="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Membership<select required value={form.membershipTypeId} onChange={e=>setForm({...form,membershipTypeId:e.target.value})}>{!form.membershipTypeId&&<option value="" disabled>Choose a plan…</option>}{plans.map(plan=><option value={plan.id} key={plan.id}>{plan.name}</option>)}</select></label><button className="primary" disabled={saving}>{saving?'Creating member…':'Create member'}</button></form></section></div>}
  </>
}
