import { Mail,Plus,Send,X } from 'lucide-react'
import { collection,onSnapshot,orderBy,query } from 'firebase/firestore'
import { useEffect,useState,type FormEvent } from 'react'
import { db,firebaseConfigured,functions } from '../../lib/firebase'
import { httpsCallable } from '../../lib/netlifyFunctions'

type Template={id:string;name:string;category:'password_reset'|'general';subject:string;body:string}
const blank:Template={id:'',name:'',category:'general',subject:'',body:'Hey {{firstName}}...\n\n\n\nPaul & Becky'}
export function EmailTemplatesPage(){
  const[items,setItems]=useState<Template[]>([]),[editing,setEditing]=useState<Template|null>(null),[sending,setSending]=useState<Template|null>(null),[form,setForm]=useState(blank),[email,setEmail]=useState(''),[firstName,setFirstName]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
  const[broadcastOpen,setBroadcastOpen]=useState(false),[broadcastSubject,setBroadcastSubject]=useState(''),[broadcastMessage,setBroadcastMessage]=useState(''),[broadcastAudience,setBroadcastAudience]=useState<'active_members'|'all_accounts'>('active_members')
  useEffect(()=>{if(!firebaseConfigured)return;return onSnapshot(query(collection(db,'emailTemplates'),orderBy('name')),snapshot=>setItems(snapshot.docs.map(item=>({id:item.id,...item.data()}) as Template)),()=>setMessage('Email templates are unavailable until Firestore rules are published.'))},[])
  function edit(item?:Template){const next=item||blank;setEditing(next);setForm({...next});setMessage('')}
  async function save(event:FormEvent){event.preventDefault();setBusy(true);setMessage('');try{const id=form.id||form.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');await httpsCallable(functions,'saveEmailTemplate')({...form,id});setEditing(null);setMessage('Email template saved.')}catch(err){setMessage(err instanceof Error&&err.message?err.message:'Template could not be saved.')}finally{setBusy(false)}}
  async function send(event:FormEvent){event.preventDefault();if(!sending)return;setBusy(true);setMessage('');try{await httpsCallable(functions,'sendTemplateEmail')({templateId:sending.id,email,firstName:firstName||undefined});setSending(null);setEmail('');setFirstName('');setMessage(`Email sent to ${email}.`)}catch(err){setMessage(err instanceof Error&&err.message?err.message:'Email could not be sent.')}finally{setBusy(false)}}
  async function broadcast(event:FormEvent){event.preventDefault();if(!confirm('Queue this urgent email to the selected audience?'))return;setBusy(true);setMessage('');try{const{data}=await httpsCallable<{subject:string;message:string;audience:string},{queued:number}>(functions,'queueUrgentBroadcast')({subject:broadcastSubject,message:broadcastMessage,audience:broadcastAudience});setBroadcastOpen(false);setBroadcastSubject('');setBroadcastMessage('');setMessage(`${data.queued} urgent emails queued safely.`)}catch(err){setMessage(err instanceof Error&&err.message?err.message:'The urgent email could not be queued.')}finally{setBusy(false)}}
  return <>
    <header className="page-head"><div><p className="eyebrow">Member communications</p><h1>Email templates</h1><p>Essential messages only—routine member activity stays inside the app.</p></div><div className="head-actions"><button className="secondary" onClick={()=>setBroadcastOpen(true)}><Send/> Urgent broadcast</button><button className="primary" onClick={()=>edit()}><Plus/> New template</button></div></header>
    {message&&<div className="notice">{message}</div>}
    <section className="email-template-grid">{items.map(item=><article className="panel" key={item.id}><span className="email-kind">{item.category==='password_reset'?'Account access':'General'}</span><Mail/><h2>{item.name}</h2><strong>{item.subject}</strong><p>{item.body.replace(/\{\{resetLink\}\}/g,'[Secure button]').replace(/\{\{firstName\}\}/g,'Firstname')}</p><div className="head-actions"><button className="secondary" onClick={()=>edit(item)}>Edit</button><button className="primary" onClick={()=>{setSending(item);setMessage('')}}><Send/> Send</button></div></article>)}{!items.length&&<article className="panel empty"><h2>No editable templates yet</h2><p>Automatic transactional messages are managed by their event triggers.</p></article>}</section>
    {broadcastOpen&&<div className="modal-backdrop"><section className="modal"><button className="modal-close" onClick={()=>setBroadcastOpen(false)}><X/></button><p className="eyebrow">Essential messages only</p><h2>Urgent member broadcast</h2><form onSubmit={broadcast}><label>Audience<select value={broadcastAudience} onChange={e=>setBroadcastAudience(e.target.value as typeof broadcastAudience)}><option value="active_members">Active members</option><option value="all_accounts">All app accounts</option></select></label><label>Subject<input required minLength={3} value={broadcastSubject} onChange={e=>setBroadcastSubject(e.target.value)}/></label><label>Message<textarea required minLength={10} rows={8} value={broadcastMessage} onChange={e=>setBroadcastMessage(e.target.value)}/></label><p className="field-hint">For urgent closures, safety information or another update members genuinely must not miss.</p><button className="primary" disabled={busy}>{busy?'Queuing safely…':'Review and queue broadcast'}</button></form></section></div>}
    {editing&&<div className="modal-backdrop"><section className="modal email-editor"><button className="modal-close" onClick={()=>setEditing(null)}><X/></button><p className="eyebrow">Reusable email</p><h2>{form.id?'Edit template':'New template'}</h2><form onSubmit={save}><label>Template name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Purpose<select disabled={!!form.id} value={form.category} onChange={e=>setForm({...form,category:e.target.value as Template['category']})}><option value="general">General email</option><option value="password_reset">Password reset</option></select></label><label>Subject<input required value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></label><label>Message<textarea required rows={12} value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></label><p className="field-hint">Use <code>{'{{firstName}}'}</code> for their name{form.category==='password_reset'&&<> and <code>{'{{resetLink}}'}</code> for the secure password button</>}.</p><button className="primary" disabled={busy}>{busy?'Saving…':'Save template'}</button></form></section></div>}
    {sending&&<div className="modal-backdrop"><section className="modal"><button className="modal-close" onClick={()=>setSending(null)}><X/></button><p className="eyebrow">Send · {sending.name}</p><h2>Who’s it going to?</h2><form onSubmit={send}><label>Email address<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>First name <small>(optional)</small><input value={firstName} onChange={e=>setFirstName(e.target.value)}/></label><p className="field-hint">Password emails create a fresh one-time reset link when you press Send.</p><button className="primary" disabled={busy}><Send/> {busy?'Sending…':'Send email'}</button></form></section></div>}
  </>
}
