import { readFile,writeFile } from 'node:fs/promises'
import { initializeApp,applicationDefault } from 'firebase-admin/app'
import { FieldValue,getFirestore } from 'firebase-admin/firestore'

const args=process.argv.slice(2),input=args.find(value=>!value.startsWith('--')),commit=args.includes('--commit')
if(!input)throw new Error('Usage: node scripts/migrate-members.mjs <members.csv> [--commit]')
function parseCsv(text){const rows=[];let row=[],field='',quoted=false;for(let index=0;index<text.length;index++){const char=text[index],next=text[index+1];if(char==='"'&&quoted&&next==='"'){field+='"';index++}else if(char==='"')quoted=!quoted;else if(char===','&&!quoted){row.push(field);field=''}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&next==='\n')index++;row.push(field);if(row.some(value=>value.trim()))rows.push(row);row=[];field=''}else field+=char}if(field||row.length){row.push(field);rows.push(row)}const headers=rows.shift()?.map(value=>value.trim())||[];return rows.map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]?.trim()||''])))}
const source=parseCsv(await readFile(input,'utf8')),required=['firstName','lastName','email','membershipTypeId'],problems=[],seen=new Map(),valid=[]
for(const[rowIndex,row]of source.entries()){const line=rowIndex+2,missing=required.filter(field=>!row[field]);if(missing.length){problems.push({line,type:'missing_fields',detail:missing.join(', ')});continue}const email=row.email.toLowerCase(),key=email||row.phone.replace(/\s/g,'');if(seen.has(key)){problems.push({line,type:'duplicate',detail:`Matches line ${seen.get(key)}`});continue}seen.set(key,line);valid.push({...row,email,membershipStatus:row.membershipStatus||'active'})}
const report={mode:commit?'commit':'dry-run',sourceRows:source.length,validRows:valid.length,problemRows:problems.length,problems}
await writeFile(`${input}.report.json`,JSON.stringify(report,null,2))
console.log(JSON.stringify(report,null,2))
if(!commit){console.log('Dry run only. Review the report, then repeat with --commit.');process.exit(problems.length?2:0)}
if(problems.length)throw new Error('Commit refused because validation problems remain.')
initializeApp({credential:applicationDefault()});const db=getFirestore(),membershipTypes=new Set((await db.collection('membershipTypes').get()).docs.map(item=>item.id)),unknown=[...new Set(valid.map(row=>row.membershipTypeId).filter(id=>!membershipTypes.has(id)))];if(unknown.length)throw new Error(`Unknown membership types: ${unknown.join(', ')}`)
let written=0,batch=db.batch();for(const row of valid){const existing=await db.collection('members').where('email','==',row.email).limit(1).get();if(!existing.empty)throw new Error(`Existing member has email ${row.email}`);const ref=db.collection('members').doc(),memberNumber=row.memberNumber||`MIG-${String(written+1).padStart(6,'0')}`;batch.create(ref,{memberNumber,firstName:row.firstName,lastName:row.lastName,email:row.email,phone:row.phone||'',membershipTypeId:row.membershipTypeId,membershipStatus:row.membershipStatus,legacySource:'spreadsheet',legacyId:row.legacyId||null,gocardlessCustomerId:row.gocardlessCustomerId||null,gocardlessMandateId:row.gocardlessMandateId||null,gocardlessSubscriptionId:row.gocardlessSubscriptionId||null,searchTokens:[row.firstName.toLowerCase(),row.lastName.toLowerCase(),row.email.toLowerCase(),memberNumber.toLowerCase()],createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});written++;if(written%400===0){await batch.commit();batch=db.batch()}}if(written%400)await batch.commit();console.log(`Imported ${written} members.`)
