import { FieldValue, getFirestore, Timestamp } from 'firebase-admin/firestore';
import { HttpsError, onCall } from 'firebase-functions/v2/https';
import { z } from 'zod';
import { requireStaff } from '../shared/auth.js';
import { generateClassSessions } from '../scheduled/classes.js';
const schema = z.object({ name: z.string().trim().min(2).max(120), description: z.string().trim().min(10).max(1200), dayOfWeek: z.number().int().min(0).max(6), startTime: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/), durationMinutes: z.number().int().min(15).max(360), location: z.string().trim().min(1).max(120), instructorNames: z.array(z.string().min(1)).min(1), defaultCapacity: z.number().int().min(1).max(500), bookingOpenDays: z.number().int().min(0).max(90).default(14), cancellationCutoffMinutes: z.number().int().min(0).max(10080).default(120) });
export const saveClassTemplate = onCall({ enforceAppCheck: true }, async (request) => { requireStaff(request); const parsed = schema.safeParse(request.data); if (!parsed.success)
    throw new HttpsError('invalid-argument', 'Recurring class details are invalid.'); const ref = getFirestore().collection('classTemplates').doc(); await ref.create({ ...parsed.data, active: true, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() }); try {
    await generateClassSessions.run({ scheduleTime: new Date().toISOString() });
}
catch { /* sessions will be topped up by the nightly job */ } return { id: ref.id }; });
const editSchema = z.object({ id: z.string().min(1), name: z.string().trim().min(2).max(120), description: z.string().trim().min(10).max(1200), location: z.enum(['Ryfields Gym', 'Ryfields Village Hall']), durationMinutes: z.number().int().min(15).max(360), instructorNames: z.array(z.string().trim().min(1).max(100)).min(1).max(10), defaultCapacity: z.number().int().min(1).max(500) });
export const editClassTemplate = onCall({ enforceAppCheck: true }, async (request) => { requireStaff(request); const parsed = editSchema.safeParse(request.data); if (!parsed.success)
    throw new HttpsError('invalid-argument', 'Recurring class details are invalid.'); const db = getFirestore(), templateRef = db.collection('classTemplates').doc(parsed.data.id), template = await templateRef.get(); if (!template.exists)
    throw new HttpsError('not-found', 'Recurring class not found.'); const sessions = await db.collection('classSessions').where('templateId', '==', parsed.data.id).get(), future = sessions.docs.filter(item => item.get('status') === 'scheduled' && (item.get('startsAt')?.toMillis() || 0) > Date.now()); if (future.some(item => Number(item.get('bookedCount') || 0) > parsed.data.defaultCapacity))
    throw new HttpsError('failed-precondition', 'Capacity cannot be lower than the number already booked on a future class.'); const changes = [String(template.get('name') || '') !== parsed.data.name ? `Class name changed to ${parsed.data.name}.` : '', String(template.get('location') || '') !== parsed.data.location ? `Location changed to ${parsed.data.location}.` : '', Number(template.get('durationMinutes') || 0) !== parsed.data.durationMinutes ? `Duration changed to ${parsed.data.durationMinutes} minutes.` : '', JSON.stringify(template.get('instructorNames') || []) !== JSON.stringify(parsed.data.instructorNames) ? `Instructor changed to ${parsed.data.instructorNames.join(', ')}.` : ''].filter(Boolean).join(' '); const batch = db.batch(); batch.update(templateRef, { name: parsed.data.name, description: parsed.data.description, location: parsed.data.location, durationMinutes: parsed.data.durationMinutes, instructorNames: parsed.data.instructorNames, defaultCapacity: parsed.data.defaultCapacity, updatedAt: FieldValue.serverTimestamp() }); for (const item of future) {
    const startsMs = item.get('startsAt').toMillis();
    batch.update(item.ref, { nameSnapshot: parsed.data.name, descriptionSnapshot: parsed.data.description, locationSnapshot: parsed.data.location, endsAt: Timestamp.fromMillis(startsMs + parsed.data.durationMinutes * 60_000), instructorNames: parsed.data.instructorNames, capacity: parsed.data.defaultCapacity, ...(changes && Number(item.get('bookedCount') || 0) > 0 ? { memberChangeAt: FieldValue.serverTimestamp(), memberChangeSummary: changes } : {}), updatedAt: FieldValue.serverTimestamp() });
} await batch.commit(); return { updatedSessions: future.length }; });
import '../config.js';
