import { CalendarDays,Dumbbell,ImagePlus,Package,Plus,Ticket,X } from 'lucide-react'
import { collection,onSnapshot,orderBy,query } from 'firebase/firestore'
import { useEffect,useMemo,useState,type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { db,firebaseConfigured,functions } from '../../lib/firebase'
import { httpsCallable } from '../../lib/netlifyFunctions'

type Category='class_passes'|'day_access'|'products'
type Product={id:string;name:string;description:string;amountMinor:number;imageDataUrl?:string|null;fulfilmentType:'manual'|'class_credits'|'day_pass';category:Category;credits:number;active:boolean;core?:boolean}
type Membership={id:string;name:string;priceMinor:number;active:boolean}
type GymEvent={id:string;title:string;active:boolean;sessionId?:string|null;type?:string|null}
type ShopOrder={id:string;productId:string;productName:string;memberId:string;memberName:string;amountMinor:number;fulfilmentStatus:'ordered'|'ready'|'delivered';paidAt?:string|null;updatedAt?:string|null}
const coreDefaults:Product[]=[
  {id:'single',name:'Single class pass',description:'One extra class whenever you need it.',amountMinor:500,fulfilmentType:'class_credits',category:'class_passes',credits:1,active:true,core:true},
  {id:'three',name:'3 class passes',description:'Three extra passes, ready in your account.',amountMinor:1500,fulfilmentType:'class_credits',category:'class_passes',credits:3,active:true,core:true},
  {id:'day',name:'One-day gym pass',description:'No membership? Train for the day. Pick a date to help you commit—the pass stays flexible.',amountMinor:600,fulfilmentType:'day_pass',category:'day_access',credits:0,active:true,core:true},
]
const blank={name:'',description:'',amountMinor:500,imageDataUrl:null as string|null,fulfilmentType:'manual' as Product['fulfilmentType'],category:'products' as Category,credits:0,active:true}
const money=(minor:number)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(minor/100)
async function imageData(file:File){const img=await createImageBitmap(file),scale=Math.min(1,1200/img.width),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d')!.drawImage(img,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.82)}

export function ShopProductsPage(){
  const[saved,setSaved]=useState<Product[]>([]),[memberships,setMemberships]=useState<Membership[]>([]),[events,setEvents]=useState<GymEvent[]>([]),[orders,setOrders]=useState<ShopOrder[]>([]),[editing,setEditing]=useState<Product|null>(null),[form,setForm]=useState(blank),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
  useEffect(()=>{if(!firebaseConfigured)return;const stops=[onSnapshot(query(collection(db,'shopProducts'),orderBy('name')),s=>setSaved(s.docs.map(d=>{const x=d.data();return{id:d.id,name:String(x.name||'Untitled item'),description:String(x.description||x.body||''),amountMinor:Number(x.amountMinor??x.priceMinor??x.price??0),imageDataUrl:x.imageDataUrl||null,fulfilmentType:['class_credits','day_pass'].includes(String(x.fulfilmentType))?x.fulfilmentType:'manual',category:['class_passes','day_access'].includes(String(x.category))?x.category:'products',credits:Number(x.credits||0),active:x.active!==false,core:['single','three','day'].includes(d.id)} as Product})),()=>setMessage('Shop items could not be loaded. Please refresh and try again.')),onSnapshot(collection(db,'membershipTypes'),s=>setMemberships(s.docs.map(d=>({id:d.id,name:String(d.get('name')||d.id),priceMinor:Number(d.get('priceMinor')||0),active:d.get('active')!==false})))),onSnapshot(collection(db,'events'),s=>setEvents(s.docs.map(d=>({id:d.id,title:String(d.get('title')||'Event'),active:d.get('active')!==false,sessionId:d.get('sessionId')||null,type:d.get('type')||null})).filter(item=>item.type==='event'||Boolean(item.sessionId))))];return()=>stops.forEach(stop=>stop())},[])
  const items=useMemo(()=>{const byId=new Map(saved.map(item=>[item.id,item]));return[...coreDefaults.map(item=>byId.has(item.id)?{...item,...byId.get(item.id)!,core:true}:item),...saved.filter(item=>!coreDefaults.some(core=>core.id===item.id))]},[saved])
  async function loadOrders(){try{const{data}=await httpsCallable<unknown,{orders:ShopOrder[]}>(functions,'listShopOrders')({});setOrders(data.orders)}catch{setMessage('Physical product orders could not be loaded.') }}
  useEffect(()=>{loadOrders()},[])
  function open(item?:Product){setEditing(item||({id:'',...blank} as Product));setForm(item?{name:item.name,description:item.description,amountMinor:item.amountMinor,imageDataUrl:item.imageDataUrl||null,fulfilmentType:item.fulfilmentType,category:item.category,credits:item.credits||0,active:item.active}:blank);setMessage('')}
  async function pick(file?:File){if(!file)return;const data=await imageData(file);if(data.length>900000){setMessage('That image is still too large—please choose a smaller graphic.');return}setForm(v=>({...v,imageDataUrl:data}))}
  async function save(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{await httpsCallable(functions,'saveShopProduct')({...form,id:editing?.id||undefined});setEditing(null);setMessage('Gym Shop item saved. The customer Shop now uses the same details and price.')}catch(err){setMessage(err instanceof Error?err.message:'Shop item could not be saved.')}finally{setBusy(false)}}
  async function remove(item:Product){if(item.core||!confirm(`Delete ${item.name}?`))return;await httpsCallable(functions,'deleteShopProduct')({id:item.id})}
  async function orderStatus(order:ShopOrder,status:ShopOrder['fulfilmentStatus']){setBusy(true);try{await httpsCallable(functions,'updateShopOrderStatus')({orderId:order.id,status});await loadOrders()}catch(err){setMessage(err instanceof Error?err.message:'Order could not be updated.')}finally{setBusy(false)}}
  const productCard=(item:Product)=>{
    const waiting=orders.filter(order=>order.productId===item.id&&order.fulfilmentStatus!=='delivered').length
    return <article className="panel shop-admin-card" id={`product-${item.id}`} key={item.id}>{item.imageDataUrl?<img src={item.imageDataUrl} alt=""/>:<div className="shop-admin-placeholder">{item.category==='class_passes'?<Ticket/>:item.category==='day_access'?<Dumbbell/>:<Package/>}</div>}<div><span className={item.active?'plan-live':'plan-off'}>{item.active?'On sale':'Hidden'}</span><h2>{item.name}</h2><p>{item.description||'No customer description yet.'}</p><strong>{item.amountMinor>0?money(item.amountMinor):'Price not set'}</strong><small>{item.fulfilmentType==='class_credits'?`${item.credits} class ${item.credits===1?'pass':'passes'}`:item.fulfilmentType==='day_pass'?'Creates a flexible day pass':'Staff fulfilment'}</small>{waiting>0&&<a className="shop-product-orders" href="#orders">{waiting} order{waiting===1?'':'s'} waiting ↑</a>}<div className="head-actions"><button className="secondary" onClick={()=>open(item)}>Edit</button>{!item.core&&<button className="secondary subtle" onClick={()=>remove(item)}>Delete</button>}</div></div></article>
  }
  return <>
    <header className="page-head"><div><p className="eyebrow">Ryfields Gym shop</p><h1>Everything you sell</h1><p>One overview. Edit passes and products here; manage memberships and events in their full settings.</p></div><button className="primary" onClick={()=>open()}><Plus/> Add product</button></header>
    {message&&<div className="notice">{message}</div>}
    <section className="shop-admin-section" id="orders"><div className="shop-admin-heading"><div><p className="eyebrow">Fulfilment</p><h2>Physical product orders</h2></div><Link className="secondary" to="/">Overview</Link></div><div className="shop-order-list">{orders.length?orders.map(order=><article className={`shop-order-row ${order.fulfilmentStatus}`} key={order.id}><span className="shop-order-state">{order.fulfilmentStatus==='delivered'?'Delivered':order.fulfilmentStatus==='ready'?'Ready':'Ordered'}</span><div><strong>{order.memberName}</strong><a href={`#product-${order.productId}`}>{order.productName}</a><small>{order.paidAt?new Date(order.paidAt).toLocaleString('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'Paid'} · {money(order.amountMinor)}</small></div><div className="head-actions">{order.fulfilmentStatus==='ordered'&&<button className="secondary" disabled={busy} onClick={()=>orderStatus(order,'ready')}>Mark ready</button>}{order.fulfilmentStatus==='ready'&&<button className="primary" disabled={busy} onClick={()=>orderStatus(order,'delivered')}>Mark delivered</button>}{order.fulfilmentStatus==='delivered'&&<button className="secondary subtle" disabled={busy} onClick={()=>orderStatus(order,'ordered')}>Reopen</button>}</div></article>):<article className="panel shop-orders-empty"><Package/><div><strong>No physical orders waiting</strong><small>New paid product orders will appear here automatically.</small></div></article>}</div></section>
    <section className="shop-admin-section"><div className="shop-admin-heading"><div><p className="eyebrow">Memberships</p><h2>Membership plans</h2></div><Link className="secondary" to="/membership-types">Manage memberships</Link></div><div className="shop-admin-grid">{[...memberships].sort((a,b)=>a.priceMinor-b.priceMinor).map(item=><article className="panel shop-link-card" key={item.id}><Dumbbell/><span className={item.active?'plan-live':'plan-off'}>{item.active?'Available':'Hidden'}</span><h2>{item.name}</h2><strong>{money(item.priceMinor)}<small>/month</small></strong><p>Membership access, billing and eligibility are managed in Membership Types.</p><Link className="secondary" to="/membership-types">Edit membership</Link></article>)}</div></section>
    <section className="shop-admin-section"><div className="shop-admin-heading"><div><p className="eyebrow">Class passes</p><h2>Extra classes</h2></div></div><div className="shop-admin-grid">{items.filter(item=>item.category==='class_passes').map(productCard)}</div></section>
    <section className="shop-admin-section"><div className="shop-admin-heading"><div><p className="eyebrow">Gym drop-ins</p><h2>Day access</h2></div></div><div className="shop-admin-grid">{items.filter(item=>item.category==='day_access').map(productCard)}</div></section>
    <section className="shop-admin-section"><div className="shop-admin-heading"><div><p className="eyebrow">Events</p><h2>Tickets and special dates</h2></div><Link className="secondary" to="/classes">Manage events</Link></div><div className="shop-admin-grid">{events.map(item=><article className="panel shop-link-card" key={item.id}><CalendarDays/><span className={item.active?'plan-live':'plan-off'}>{item.active?'Showing':'Hidden'}</span><h2>{item.title}</h2><strong>{item.sessionId?'Bookable event':'Notice only'}</strong><p>Timing, capacity, artwork and tickets are managed from Classes → Noticeboard.</p><Link className="secondary" to="/classes">Edit event</Link></article>)}{!events.length&&<article className="panel empty"><h2>No events yet</h2><p>Add one from Classes → Noticeboard.</p></article>}</div></section>
    <section className="shop-admin-section"><div className="shop-admin-heading"><div><p className="eyebrow">Products</p><h2>Gym products</h2></div><button className="primary compact" onClick={()=>open()}><Plus/> Add product</button></div><div className="shop-admin-grid">{items.filter(item=>item.category==='products').map(productCard)}{!items.some(item=>item.category==='products')&&<article className="panel empty"><Package/><h2>No products yet</h2><p>Protein, drinks, clothing and anything else you add will appear here.</p></article>}</div></section>
    {editing&&<div className="modal-backdrop"><section className="modal"><button className="modal-close" onClick={()=>setEditing(null)}><X/></button><p className="eyebrow">Gym Shop item</p><h2>{editing.id?'Edit item':'Add product'}</h2><form onSubmit={save}><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Description<textarea required rows={5} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Shop section<select value={form.category} disabled={editing.core} onChange={e=>setForm({...form,category:e.target.value as Category})}><option value="class_passes">Class passes</option><option value="day_access">Drop-in gym access</option><option value="products">Products</option></select></label><label>Price (£)<input required type="number" min="0.5" step="0.01" value={form.amountMinor/100} onChange={e=>setForm({...form,amountMinor:Math.round(Number(e.target.value)*100)})}/></label><label className="shop-image-pick"><ImagePlus/> Product graphic<input type="file" accept="image/*" onChange={e=>pick(e.target.files?.[0])}/></label>{form.imageDataUrl&&<img className="shop-admin-preview" src={form.imageDataUrl} alt="Preview"/>}<label>After payment<select value={form.fulfilmentType} disabled={editing.core} onChange={e=>setForm({...form,fulfilmentType:e.target.value as Product['fulfilmentType']})}><option value="manual">Flag for staff to fulfil</option><option value="class_credits">Add class passes automatically</option><option value="day_pass">Create a gym day pass</option></select></label>{form.fulfilmentType==='class_credits'&&<label>Number of class passes<input type="number" min="1" max="100" value={form.credits} onChange={e=>setForm({...form,credits:Number(e.target.value)})}/></label>}<label className="checkbox"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Show in the customer Shop</label><button className="primary" disabled={busy}>{busy?'Saving…':'Save item everywhere'}</button></form></section></div>}
  </>
}
